# vim ft=yaml
language: python

env:
  global:
    - DEPENDS="requirements.txt"
    - COVERAGE=1

python:
  - 3.4
  - 2.7

install:
  - source tools/travis_tools.sh
  - virtualenv --python=python venv
  - source venv/bin/activate
  - python --version # just to check
  - retry pip install nose # always
<<<<<<< HEAD
  - cd data && make testdata && cd ..
=======
  - cd data && make testing_data && cd ..
>>>>>>> 151a80b3392ce18e09dd52cad2a0b6c2d84503de
  - sudo apt-get install libblas-dev liblapack-dev libatlas3gf-base
  - wheelhouse_pip_install ${DEPENDS}
  - if [ "${COVERAGE}" == "1" ]; then
    pip install coverage;
    pip install coveralls;
    fi

script:
  - make coverage


after_success:
  - if [ "${COVERAGE}" == "1" ]; then coveralls; fi
